### ISSUE TITLE
Creating a User

### ISSUE THREAD

**Issue by mihaip007** [vdespa/Vtiger-Web-Services-PHP-Client-Library#10]
Hi - I tried creating a user account but I get access denied even though I am using an Admin username.
Would you be able to advise me where I should look at to fix this matter?
Thank you in advance...
Here is the code: 
`$res = $wsclient->createObject('Users', [
        'user_name'         => 'test123',
        'user_password'     => 'foobar',
        'confirm_password'  => 'foobar',
        'email1'            => 'foo@bar.com',
        'first_name'        => 'Bar',
        'last_name'         => 'Bar',
        'status'            => 'Active',
        'roleid'            => 'H2',
    ]);`

and here is the output:

> (
            [code] => ACCESS_DENIED
            [message] => Permission to perform the operation is denied for id
        )

**Comment by vdespa** [comment]
Sorry, I am not maintaining this project anymore. The code has not been updated in 3 years. So I would advise you look into other solutions.
