### ISSUE TITLE
 Undefined index: testing

### ISSUE THREAD

**Issue by Skatox** [vdespa/Vtiger-Web-Services-PHP-Client-Library#5]
Hello I had problem with this file **vdespa/vtiger/src/WSClient.php(115)** because it assumes that config have a 'testing' value but it doesn't. I have to pass to the config array a 'testing' key without any value to make it work.

Do you mind if I send you fix? Or do you do it?

**Comment by vdespa** [comment]
How can I mind :) Please submit a PR. I will review it as soon as possible. 

Thanks for your help.

**Comment by Skatox** [comment]
Nice, I've made a pull request [e4cb0aa]. Thanks for creating this library
